name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Windows Server
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Deployment Script
        shell: powershell
        run: |
          .\deploy.ps1
