name: Debug Environment
        shell: powershell
        run: |
          Write-Host "Current Location: $(Get-Location)"
          Get-ChildItem  # This lists files to verify deploy.ps1 is there
          npm --version
          pm2 --version
          .\deploy.ps1
